### ISSUE TITLE
I want to know how to run this project successfully

### ISSUE THREAD

**Issue by Haydn-C** [weiba/NIHGCN#1]
I wonder if I only need to run main.py if I want to run this project successfully.As is shown in the screenshot when I ran this code I meet some errors.After I google this error,I learn that it may because the packages have not been installed.But I have installed all the packages metioned in the github.This make me more confused.
This is my first time asking a question on github and my English is not very good.Please forgive me if I have offended you.Looking forward to your reply if you are free.
![screenshot](https://user-images.githubusercontent.com/96980693/233718765-ae0353a4-fc43-4702-955c-ada7e34674f9.png)

I added a text version error because I was worried that the screenshot upload would fail:

F:\Anaconda3\envs\python38\python.exe E:\pythonproject\NIHGCN-master\External\main.py 
Traceback (most recent call last):
  File "E:\pythonproject\NIHGCN-master\External\main.py", line 3, in <module>
    from load_data import load_data
  File "E:\pythonproject\NIHGCN-master\load_data.py", line 1, in <module>
    from myutils import *
  File "E:\pythonproject\NIHGCN-master\myutils.py", line 7, in <module>
    import seaborn as sns
  File "F:\Anaconda3\envs\python38\lib\site-packages\seaborn\__init__.py", line 2, in <module>
    import matplotlib as mpl
  File "F:\Anaconda3\envs\python38\lib\site-packages\matplotlib\__init__.py", line 113, in <module>
    from . import _api, _version, cbook, _docstring, rcsetup
  File "F:\Anaconda3\envs\python38\lib\site-packages\matplotlib\rcsetup.py", line 27, in <module>
    from matplotlib.colors import Colormap, is_color_like
  File "F:\Anaconda3\envs\python38\lib\site-packages\matplotlib\colors.py", line 51, in <module>
    from PIL import Image
  File "F:\Anaconda3\envs\python38\lib\site-packages\PIL\Image.py", line 103, in <module>
    from . import _imaging as core
ImportError: DLL load failed while importing _imaging: 找不到指定的模块。

**Comment by weiba** [comment]
This error is usually due to the environment not being configured properly.
I think you can just delete "import seaborn as snsy" at line 7 and "def
gather_color_code" at line 625 in the file myutils.py.

Dalayandingdong ***@***.***> 于2023年4月22日周六 03:30写道：

**Comment by Haydn-C** [comment]
Thank you very much for your answer, I solved that problem by changing the python environment and reinstalling the package.
However, now I have encountered a new problem. In README.md, you mentioned that cell_exprs.csv cannot be uploaded due to the limitation of github, so it is divided into several parts in the compressed file. I tried to restore it, but I'm not very familiar with the data yet so I'm afraid of messing it up. In order to successfully run this project, I hope you can send me the source code and original data of the project by email.
This is my email: dalayandingdong@gmail.com
Thank you for your time in advance and I am looking forward to hearing from you soon.
